version: '3'

services:
  web:
    restart: always
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app
  
  redis:
    restart: always
    image: "redis:7.0.11"
    ports:
      - "6379:6379"
    volumes:
      - ./dump.rdb:/data/dump.rdb
    networks:
      - app
  
  db:
    restart: always
    image: "mariadb:10.11.4"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gestionProjet
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app

volumes:
  db_data:

networks:
    app:
      name: app
      external: false



