name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - charlelie
  pull_request:
    branches:
      - main
      - charlelie

env:
  SONAR_USER_HOME: ${{ github.workspace }}/.sonar
  GIT_DEPTH: "0"

jobs:
  sonarcloud-check:
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli:latest
      options: --entrypoint ""
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: .sonar/cache
        key: sonarcloud-${{ github.job }}
    - name: Run sonar-scanner
      run: sonar-scanner

  build:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm test

      # Terraform setup and execution
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        
      - name: Terraform Init
        run: |
          cd azure-migration
          terraform init
      - name: Terraform Apply
        run: |
          cd azure-migration
          terraform apply -auto-approve \
            -var="subscription_id=${{ secrets.DATABASE_USER }}" \
            -var="admin_login=${{ secrets.DATABASE_USER }}" \
            -var="admin_password=${{ secrets.DATABASE_PASSWORD }}"
